; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2.1.2 on Sat Nov 09 2019 16:11:57 GMT+0100 (Central European Standard Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


