; homeall.g
; called to home all axes
;
; generated by RepRapFirmware Configuration Tool v2.1.2 on Sat Nov 09 2019 16:11:57 GMT+0100 (Central European Standard Time)
                     
M98 P"homex.g"
M98 P"homey.g"
M98 P"homez.g"                  




