; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2.1.2 on Sat Nov 09 2019 16:11:58 GMT+0100 (Central European Standard Time)

